//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCredito.ICreditoService")]
    public interface ICreditoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ListarCredito", ReplyAction="http://tempuri.org/ICreditoService/ListarCreditoResponse")]
        Pacagroup.Comercial.Creditos.Dominio.Credito[] ListarCredito();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ListarCredito", ReplyAction="http://tempuri.org/ICreditoService/ListarCreditoResponse")]
        System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Credito[]> ListarCreditoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/RegistrarCredito", ReplyAction="http://tempuri.org/ICreditoService/RegistrarCreditoResponse")]
        Pacagroup.Comercial.Creditos.Dominio.Credito RegistrarCredito(Pacagroup.Comercial.Creditos.Dominio.Credito pCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/RegistrarCredito", ReplyAction="http://tempuri.org/ICreditoService/RegistrarCreditoResponse")]
        System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Credito> RegistrarCreditoAsync(Pacagroup.Comercial.Creditos.Dominio.Credito pCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ActualizarCredito", ReplyAction="http://tempuri.org/ICreditoService/ActualizarCreditoResponse")]
        Pacagroup.Comercial.Creditos.Dominio.Credito ActualizarCredito(Pacagroup.Comercial.Creditos.Dominio.Credito pCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ActualizarCredito", ReplyAction="http://tempuri.org/ICreditoService/ActualizarCreditoResponse")]
        System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Credito> ActualizarCreditoAsync(Pacagroup.Comercial.Creditos.Dominio.Credito pCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/EliminarCredito", ReplyAction="http://tempuri.org/ICreditoService/EliminarCreditoResponse")]
        bool EliminarCredito(string idCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/EliminarCredito", ReplyAction="http://tempuri.org/ICreditoService/EliminarCreditoResponse")]
        System.Threading.Tasks.Task<bool> EliminarCreditoAsync(string idCredito);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreditoServiceChannel : Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.ICreditoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditoServiceClient : System.ServiceModel.ClientBase<Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.ICreditoService>, Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.ICreditoService {
        
        public CreditoServiceClient() {
        }
        
        public CreditoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pacagroup.Comercial.Creditos.Dominio.Credito[] ListarCredito() {
            return base.Channel.ListarCredito();
        }
        
        public System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Credito[]> ListarCreditoAsync() {
            return base.Channel.ListarCreditoAsync();
        }
        
        public Pacagroup.Comercial.Creditos.Dominio.Credito RegistrarCredito(Pacagroup.Comercial.Creditos.Dominio.Credito pCredito) {
            return base.Channel.RegistrarCredito(pCredito);
        }
        
        public System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Credito> RegistrarCreditoAsync(Pacagroup.Comercial.Creditos.Dominio.Credito pCredito) {
            return base.Channel.RegistrarCreditoAsync(pCredito);
        }
        
        public Pacagroup.Comercial.Creditos.Dominio.Credito ActualizarCredito(Pacagroup.Comercial.Creditos.Dominio.Credito pCredito) {
            return base.Channel.ActualizarCredito(pCredito);
        }
        
        public System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Credito> ActualizarCreditoAsync(Pacagroup.Comercial.Creditos.Dominio.Credito pCredito) {
            return base.Channel.ActualizarCreditoAsync(pCredito);
        }
        
        public bool EliminarCredito(string idCredito) {
            return base.Channel.EliminarCredito(idCredito);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarCreditoAsync(string idCredito) {
            return base.Channel.EliminarCreditoAsync(idCredito);
        }
    }
}
